# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

include_guard(GLOBAL)

function(forfun_clang_properties target)
  if(FORFUN_ENABLE_STRICT_COMPILATION)
    target_compile_options(
    "${target}"
    PRIVATE
      $<$<COMPILE_LANG_AND_ID:C,Clang>:
        -pedantic
        -Weverything
        -Wall
        -Walloca
        -Warray-bounds
        -Warray-bounds-pointer-arithmetic
        -Warray-parameter
        -Wassign-enum
        -Wbad-function-cast
        -Wbitwise-op-parentheses
        -Wcast-align
        -Wcast-function-type
        -Wcast-qual
        -Wcomplex-component-init
        -Wconditional-uninitialized
        -Wconversion
        -Wcovered-switch-default
        -Wdate-time
        -Wdeclaration-after-statement
        -Wdeprecated
        -Wdouble-promotion
        -Wempty-body
        -Wextra
        -Wextra-semi
        -Wfloat-equal
        -Wformat-signedness
        -Wformat=2
        -Wframe-address
        -Wgnu
        -Wimplicit-fallthrough
        -Wimplicit-function-declaration
        -Wimplicit-int
        -Winit-self
        -Wliteral-conversion
        -Wliteral-range
        -Wlogical-op-parentheses
        -Wmisleading-indentation
        -Wmissing-braces
        -Wmissing-declarations
        -Wmissing-field-initializers
        -Wmissing-include-dirs
        -Wmissing-noreturn
        -Wmissing-prototypes
        -Wmissing-variable-declarations
        -Wnull-dereference
        -Wnull-pointer-arithmetic
        -Wold-style-definition
        -Wparentheses
        -Wpointer-arith
        -Wredundant-parens
        -Wshadow-all
        -Wsign-compare
        -Wsign-conversion
        -Wsometimes-uninitialized
        -Wstack-protector
        -Wstrict-overflow=5
        -Wstrict-prototypes
        -Wswitch
        -Wswitch-default
        -Wswitch-enum
        -Wtautological-compare
        -Wtautological-constant-in-range-compare
        -Wunaligned-access
        -Wundef
        -Wuninitialized
        -Wunreachable-code-aggressive
        -Wunsequenced
        -Wunused
        -Wunused-macros
        -Wvla
        -Wwrite-strings
      >
      $<$<COMPILE_LANG_AND_ID:CXX,Clang>:
        -fsafe-buffer-usage-suggestions
        -pedantic
        -Wabstract-vbase-init
        -Waddress-of-temporary
        -Wall
        -Walloca
        -Wanon-enum-enum-conversion
        -Wargument-outside-range
        -Warray-bounds-pointer-arithmetic
        -Warray-parameter
        -Wassign-enum
        -Watomic-implicit-seq-cst
        -Wbind-to-temporary-copy
        -Wbitfield-enum-conversion
        -Wbitwise-op-parentheses
        -Wbool-conversion
        -Wbool-operation
        -Wcast-align
        -Wcast-function-type
        -Wcast-qual
        -Wcomplex-component-init
        -Wconditional-uninitialized
        -Wconversion
        -Wcovered-switch-default
        -Wdate-time
        -Wdelete-non-virtual-dtor
        -Wdeprecated
        -Wdouble-promotion
        -Wdynamic-exception-spec
        -Wempty-body
        -Wexit-time-destructors
        -Wextra
        -Wextra-semi
        -Wfloat-equal
        -Wfor-loop-analysis
        -Wformat-signedness
        -Wformat=2
        -Wframe-address
        -Wglobal-constructors
        -Wgnu
        -Wimplicit-fallthrough
        -Wimplicit-float-conversion
        -Wimplicit-int-conversion
        -Wimplicit-int-float-conversion
        -Winit-self
        -Winline
        -Winvalid-offsetof
        -Wliteral-conversion
        -Wliteral-range
        -Wlogical-op-parentheses
        -Wloop-analysis
        -Wmethod-signatures
        -Wmisleading-indentation
        -Wmissing-braces
        -Wmissing-declarations
        -Wmissing-include-dirs
        -Wmissing-noreturn
        -Wmissing-prototypes
        -Wmove
        -Wnarrowing
        -Wnon-virtual-dtor
        -Wnull-dereference
        -Wnull-pointer-arithmetic
        -Wold-style-cast
        -Woverloaded-virtual
        -Wpacked
        -Wpacked-non-pod
        -Wparentheses
        -Wpointer-arith
        -Wrange-loop-analysis
        -Wredundant-move
        -Wredundant-parens
        -Wself-assign
        -Wself-move
        -Wshadow-all
        -Wsign-compare
        -Wsign-conversion
        -Wsometimes-uninitialized
        -Wstack-protector
        -Wstrict-overflow=5
        -Wstrict-selector-match
        -Wsuggest-destructor-override
        -Wsuggest-override
        -Wswitch-default
        -Wswitch-enum
        -Wtautological-compare
        -Wtautological-constant-in-range-compare
        -Wthread-safety
        -Wthread-safety-beta
        -Wunaligned-access
        -Wundef
        -Wuninitialized
        -Wunreachable-code
        -Wunreachable-code-aggressive
        -Wunsequenced
        -Wunused
        -Wunused-macros
        -Wunused-parameter
        -Wunused-variable
        -Wweak-vtables
        -Wzero-as-null-pointer-constant
        -Wno-c++98-c++11-compat-binary-literal
        -Wno-c++98-compat
        -Wno-c++98-compat-bind-to-temporary-copy
        -Wno-c++98-compat-pedantic
        -Wno-nrvo
        -Wno-padded
        -Wno-pre-c++20-compat-pedantic
        -Wno-unsafe-buffer-usage
      >
    )
  endif()

  if(FORFUN_CONFIGURE_CODE_COVERAGE)
    target_compile_options(
      "${target}"
      PRIVATE
        -fcoverage-mapping
        -fprofile-instr-generate
    )

    target_link_options(
      "${target}"
      PRIVATE
        -fprofile-instr-generate
    )
  endif()

  if(FORFUN_TSAN_BUILD)
    target_compile_options(
    "${target}"
    PRIVATE
      $<$<COMPILE_LANG_AND_ID:C,AppleClang,Clang>:
        -fsanitize=thread
        -fno-omit-frame-pointer
        -fno-sanitize-recover=all
        -fPIE
      >
      $<$<COMPILE_LANG_AND_ID:CXX,AppleClang,Clang>:
        -fsanitize=thread
        -fno-omit-frame-pointer
        -fno-sanitize-recover=all
        -fPIE
      >
    )

    target_link_options(
      "${target}"
      PRIVATE
        -fsanitize=thread
        -pie
        -flto
        -fno-omit
    )
  endif()

  if(FORFUN_ASAN_UBSAN_BUILD)
    target_compile_options(
    "${target}"
    PRIVATE
      $<$<COMPILE_LANG_AND_ID:C,AppleClang,Clang>:
        -fsanitize=address
        -fsanitize-address-use-after-return=always
        -fsanitize-address-use-after-scope
        -fsanitize=float-divide-by-zero,implicit-conversion,local-bounds,nullability,undefined,vptr
        -fno-omit-frame-pointer
        -fno-sanitize-recover=all
      >
      $<$<COMPILE_LANG_AND_ID:CXX,AppleClang,Clang>:
        -fsanitize=address
        -fsanitize-address-use-after-return=always
        -fsanitize-address-use-after-scope
        -fsanitize=float-divide-by-zero,implicit-conversion,local-bounds,nullability,undefined,vptr
        -fno-omit-frame-pointer
        -fno-sanitize-recover=all
      >
    )

    target_link_options(
      "${target}"
      PRIVATE
        -fsanitize=address
        -fsanitize-address-use-after-return=always
        -fsanitize-address-use-after-scope
        -fsanitize=float-divide-by-zero,implicit-conversion,local-bounds,nullability,undefined,vptr
        -flto
        -fno-omit-frame-pointer
        -fno-sanitize-recover=all
        -fvisibility=default
    )
  endif()
endfunction()
