# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

include_guard(GLOBAL)

function(forfun_gcc_properties target)
  if(FORFUN_ENABLE_STRICT_COMPILATION)
    target_compile_options(
    "${target}"
    PRIVATE
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang>:
        -pedantic
        -Wall
        -Wextra
        -Walloc-zero
        -Wcast-align=strict
        -Wcast-qual
        -Wconversion
        -Wdate-time
        -Wdisabled-optimization
        -Wdouble-promotion
        -Wduplicated-branches
        -Wduplicated-cond
        -Wformat=2
        -Wformat-overflow=2
        -Wformat-truncation=2
        -Wimplicit-fallthrough=5
        -Winit-self
        -Wlogical-op
        -Wmisleading-indentation
        -Wmissing-declarations
        -Wmissing-noreturn
        -Wmissing-prototypes
        -Wmultichar
        -Wnested-externs
        -Wnonnull
        -Wnull-dereference
        -Wold-style-definition
        -Wopenacc-parallelism
        -Wpacked
        -Wpacked-bitfield-compat
        -Wpointer-arith
        -Wredundant-decls
        -Wreturn-type
        -Wsequence-point
        -Wshadow=global
        -Wshift-negative-value
        -Wsign-conversion
        -Wstrict-overflow=5
        -Wstrict-prototypes
        -Wswitch
        -Wswitch-enum
        -Wtrampolines
        -Wundef
        -Wunused
        -Wunused-macros
        -Wunused-parameter
        -Wunused-variable
        -Wvla
        -Wwrite-strings
        -Wunsafe-loop-optimizations
        -fstack-protector-strong
        -fstrict-flex-arrays
        -fanalyzer
      >
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang>:
        -pedantic
        -Wall
        -Wextra
        -Wcast-align=strict
        -Wcast-qual
        -Wconversion
        -Wctor-dtor-privacy
        -Wdangling-pointer
        -Wdangling-reference
        -Wdate-time
        -Wdelete-non-virtual-dtor
        -Wdeprecated-copy
        -Wdeprecated-enum-enum-conversion
        -Wdeprecated-enum-float-conversion
        -Wdouble-promotion
        -Wduplicated-branches
        -Wduplicated-cond
        -Wformat=2
        -Wimplicit-fallthrough=5
        -Winaccessible-base
        -Winherited-variadic-ctor
        -Winit-list-lifetime
        -Winit-self
        -Winvalid-constexpr
        -Winvalid-offsetof
        -Wlogical-op
        -Wmisleading-indentation
        -Wmismatched-new-delete
        -Wmismatched-tags
        -Wmissing-declarations
        -Wmissing-noreturn
        -Wmissing-requires
        -Wmultichar
        -Wnarrowing
        -Wnon-template-friend
        -Wnon-virtual-dtor
        -Wnull-dereference
        -Wold-style-cast
        -Woverlength-strings
        -Woverloaded-virtual
        -Wpacked
        -Wpacked-bitfield-compat
        -Wrange-loop-construct
        -Wredundant-decls
        -Wredundant-move
        -Wredundant-tags
        -Wreorder
        -Wself-move
        -Wshadow=global
        -Wshift-negative-value
        -Wsign-conversion
        -Wsign-promo
        -Wsized-deallocation
        -Wstack-protector
        -Wstrict-null-sentinel
        -Wstrict-overflow=2
        -Wunused
        -Wunused-macros
        -Wuseless-cast
        -Wvariadic-macros
        -Wvector-operation-performance
        -Wvexing-parse
        -Wvirtual-move-assign
        -Wvla
        -Wwrite-strings
        -Wzero-as-null-pointer-constant
        -Walloc-zero
        -Wunsafe-loop-optimizations
      >
    )
  endif()

  if(FORFUN_CONFIGURE_CODE_COVERAGE)
    target_compile_options(
      "${target}"
      PRIVATE
        --coverage
    )

    target_link_options(
      "${target}"
      PRIVATE
        --coverage
    )
  endif()
endfunction()
