# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Dependency review

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: 10 22 * * 3
  workflow_dispatch:

permissions: {}

jobs:
  dependency-review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Review dependencies
        uses: actions/dependency-review-action@v5
        with:
          base-ref: ${{ github.event.pull_request.base.sha || 'main' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
